#!/usr/bin/env bash

if [ -n "$2" ]; then
    exit
fi

# Skip if a string like 'squash!' is included in the original message
if grep --quiet -P "^\\w+!" "$1"; then
    exit 0
fi
COMMIT=$(git symbolic-ref HEAD)
# Generate a commit message from the diff of the commit
IFS=$'\n'
for s in $(git --no-pager diff --cached --name-status "$COMMIT"); do
    if [[ "$s" =~ setup-([^.]+) ]]; then
        FILENAME=${BASH_REMATCH[1]}
        # Prevent from inserting a message if the file is setup-misc.el
        if [[ ${FILENAME} =~ ^(meta|misc)$ ]]; then
            continue
        fi
        # Insert a line into the message depending on the status of the file
        STATUS=${s:0:1}
        case ${STATUS} in
            M)
                sed -i "1i[${FILENAME}] \n" "$1"
                ;;
            A)
                sed -i "1iAdd ${FILENAME}\n" "$1"
                ;;
        esac
    elif [[ "$s" =~ lisp/my/([^.]+)\.el ]]; then
        sed -i "1i${BASH_REMATCH[1]}: " "$1"
    elif [[ "$s" =~ meta/ ]] || [[ "$s" =~ .githooks/ ]]; then
        sed -i "1iMeta: " "$1"
    elif [[ "$s" =~ README ]]; then
        sed -i "1iDoc: " "$1"
    fi
done
