language: generic
cache:
  - directories:
      - $HOME/.evm
matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis
    - env: EVM_EMACS=emacs-25.1-travis
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
before_install:
  - (cd $HOME/.evm && git pull) || git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - emacs --version
install:
  - ln -s $PWD $HOME/.emacs.d
script:
  - emacs -Q --batch -f batch-byte-compile init.el
notifications:
  email:
    on_success: never
    on_failure: always
