language: generic
sudo: false
cache:
  - directories:
      - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.3
  - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - emacs --version
install:
  - ln -s $PWD $HOME/.emacs.d
script:
  - emacs --batch -l init.el
notifications:
  email:
    on_success: never
    on_failure: always