#+title: Emacs

See also [[file:README.org]]

* Contents :noexport:
:PROPERTIES:
:TOC:      this
:END:
  -  [[#policies][Policies]]
    -  [[#shells-and-terminals][Shells and terminals]]
    -  [[#common-keybindings-for-navigation-in-a-list][Common keybindings for navigation in a list]]
    -  [[#using-menu-key-for-help][Using menu key for help]]
    -  [[#org-capture-templates][org-capture templates]]
  -  [[#tips][Tips]]
    -  [[#manage-local-and-remote-repositories][Manage local and remote repositories]]
      -  [[#use-helm-repom-to-open-a-repository][Use =helm-repom= to open a repository]]
      -  [[#cleaning-up-the-list][Cleaning up the list]]
    -  [[#scratch-buffers][Scratch buffers]]
    -  [[#check-todos][Check todos]]
      -  [[#navigate-through-a-buffer-by-todo-keywords][Navigate through a buffer by todo keywords]]
      -  [[#magit-todos][magit-todos]]
    -  [[#ibuffer-sidebar-and-dired-sidebar][ibuffer-sidebar and dired-sidebar]]
      -  [[#dired-sidebar][dired-sidebar]]
      -  [[#ibuffer-sidebar][ibuffer-sidebar]]
    -  [[#search][Search]]
      -  [[#find-documentation][Find documentation]]
      -  [[#web-search][Web search]]
    -  [[#editing-org-mode][Editing org-mode]]
      -  [[#graphics-and-images-in-org-mode][Graphics and images in Org Mode]]
    -  [[#using-pandoc-for-document-conversion][Using pandoc for document conversion]]
    -  [[#japanese-support-through-katawa][Japanese support through Katawa]]
  -  [[#issues][Issues]]

* Policies                                                           :policy:
:PROPERTIES:
:TOC:      1
:END:
** Shells and terminals
:PROPERTIES:
:CREATED_TIME: [2018-08-19 Sun 18:07]
:ID:       a880c587-5b67-4510-96a8-0839e6d32961
:END:
*** Prefer eshell
:PROPERTIES:
:ID:       a2c30e8c-6aca-4cf1-a9df-4fdd674d07c0
:END:
I haven't used eshell frequently since I have started using Emacs, but I will give it a try. The primary reason for this is that it works the same in all operating systems, including Windows. I have been using Linux as my primary desktop operating system for several years, but I am going to use Windows at work, so I will try eshell.

The default configuration of eshell is not very sophisticated compared to fish or well-configured zsh. You can tweak eshell in Emacs Lisp, but there is a package named [[https://github.com/manateelazycat/aweshell][aweshell]], which makes eshell like fish. I will use it: [[file:apps/init-aweshell.el][init-aweshell.el]]

Advantages of using eshell:

- Cross-platform: Eshell can be used as an alternative UNIX-like shell for non-UNIX platforms, e.g. Windows.
- Integration with TRAMP.
- You can operate on Emacs Lisp lists easily in shells.
- A good emulation of bash (compared to fish).
- Extensible in Emacs Lisp.

Limitations of eshell (with aweshell):

- With the default configuration, aweshell starts slower than fish.
- Not fully compliant with bash. For example, =!!= is supported in esehell, but =!$= is not supported.
- Eshell is not a terminal emulator, so terminal applications like =htop= will not run on it.

References:

- [[https://masteringemacs.org/article/complete-guide-mastering-eshell][Mastering Eshell - Mastering Emacs]]
- [[http://ergoemacs.org/emacs/eshell.html][Emacs: eshell - Ergomacs]]
- [[http://ergoemacs.org/emacs/emacs_shell_vs_term_vs_ansi-term_vs_eshell.html][Emacs: Difference between shell, term, eshell]]

** Common keybindings for navigation in a list                  :keybinding:
Some Emacs applications display a list of items and let you browse them. These applications innclude dired, magit, and "sidebar" applications. You might sometimes prefer switching focus to a browsed item, but otherwise you might prefer keeping focus. You need separate bindings for opening an item. I basically prefer the following bindings for this kind of commands:

- ~RET~ to open an item and switch focus
- ~SPC~ to open an item in another window but keep focus in the original window

These bindings are applicable to the following major modes in my configuration:

- magit-status (including magit-todos)
- dired-sidebar
** Using menu key for help                      :help:keybinding:microhabit:
Use ~<menu>~ key as a prefix for alternative help commands. Especially, the following kinds of commands should bound on this prefix:

- Help/referencing commands specific to modes of the current buffer.
- Dictionary commands (for natural languages).

There is already ~<f1>~ (or ~C-h~ by default) for help commands, but these are about Emacs. If you want to get a context-specific help, try ~<menu>~.

*** Tutorial hydra                       :microhabit:keybinding:help:hydra:
By convention, ~<menu> h~ should be bound to a Hydra command for the major mode.
** org-capture templates                     :Org_Mode:note_taking:org__protocol:
*** org-default-notes vs. the clock target
My =org-capture-templates= variable is configured to allow quickly capturing certain kinds of information to some location. Some location means the clocked task when there is a running clock and otherwise =org-default-notes-file=. This was inspired from [[http://www.howardism.org/Technical/Emacs/capturing-content.html][Capturing Content for Emacs]]:

| Type              | Clock | Default |
|-------------------+-------+---------|
| Task (entry)      | ~t~   | ~dt~    |
| Plain             | ~a~   | N/A     |
| List item         | ~i~   | N/A     |
| org-protocol link | ~L~   | ~dL~    |
| org-protocol note | ~p~   | ~dp~    |

A few notes:

- When no running clock is running, templates with the default target (beginning with ~d~) are "lifted" to keys without the prefix. You can use ~t~ to create a task, ~L~ to create a protocol, etc.
- When no clock is running, the protocol link template creates an entry in the default file. When a clock is running, the protocol link template creates an item under the clocked task.

These templates are configured through =org-starter-initial-capture-templates= variable in my =org-starter= package ([[file:org/init-org-starter.el]]), because I also configure some other templates elsewhere using =org-starter=. Also note that this variable is set using =general-setq=.
**** TODO org-protocol
Configure org-protocol properly. The current templates may not work.
*** Templates to specific files
Templates that capture into specific files can be configured within =org-starter-define-file=. Use =:capture= option.
* Tips
:PROPERTIES:
:TOC:      2
:END:
** Manage local and remote repositories
:PROPERTIES:
:ID:       96328360-8a53-47d6-afbb-d7b90aaea751
:END:
Use repom package to manage local and remote repositories: [[file:misc/init-repom.el]]
*** Use =helm-repom= to open a repository
I used =counsel-projectile-switch-project= for opening a local repository, but now that I have =repom=, I will use =helm-repom= to open a repository. If a repository is not available locally, then I can clone it from a remote server quickly.

- [[file:misc/init-repom.el]]
*** Cleaning up the list
I have to maintain =projectile-known-projects= regularly:

- [X] Delete duplicates
- [X] Delete projects that no longer exists
- [ ] For repositories in some locations (e.g. straight packages), they should be deleted from the list unless they are in a dirty state

These tasks are completed by =projectile-cleanup-known-projects=. This is triggered by midnight-mode: [[file:misc/init-midnight.el]].
** Scratch buffers                                              :microhabit:
Use scratch buffer extensively: [[file:coding/init-scratch.el]]
** Check todos
[[https://github.com/tarsius/hl-todo][hl-todo]] package highlights todo keywords in buffers: [[file:coding/init-hl-todo.el::(use-package%20hl-todo][init-hl-todo.el]]
*** ARCHIVED Navigate through a buffer by todo keywords        :keybinding:
CLOSED: [2018-07-04 Wed 01:49]
:LOGBOOK:
- State "ARCHIVED"   from "TODO"       [2018-07-04 Wed 01:49] \\
  I probably don't need this feature, as magit-todos provides a todo list.
:END:
Bind keys to the following commands:

- [ ] =hl-todo-next/previous= commands
- [ ] =hl-todo-occur= command
*** magit-todos
[[file:apps/init-magit.el::(use-package%20magit-todos][magit-todos]] enhances =magit-status= to show todo items in files in the project.
** ibuffer-sidebar and dired-sidebar
There are several sidebar packages for Emacs. I once used treemacs, which was well-developed, but I don't always need a sidebar, and I don't want to learn new keybindings for less frequently applications. dired-sidebar and ibuffer-sidebar are based on dired and ibuffer respectively, so I will try to use it.

Configuration: [[file:ui/init-sidebar.el]]
*** dired-sidebar
**** DONE Tweak the keybindings in dired-sidebar buffer
CLOSED: [2018-08-12 Sun 05:46]
- [X] ~RET~ to open the file in a non-sidebar window
- [X] ~SPC~ to open the file in a non-sidebar window but keep focus in the sidebar
*** ibuffer-sidebar
**** Add support for frame-purpose.el to ibuffer-sidebar
I've added an experimental support for frame-purpose. This can replace the built-in sidebar of frame-purpose.
** REVIEW Search
:PROPERTIES:
:ID:       9d45eb85-dc93-425c-9564-c4e4b0e0a489
:END:
:LOGBOOK:
- State "REVIEW"     from              [2018-07-04 Wed 15:27]
:END:
*** Find documentation
- [[file:misc/init-web-search.el::(defun%20akirak/helm-search-symbol-at-point%20()][akirak/helm-search-symbol-at-point]] command lets you choose a search engine for a symbol under the cursor.
  - I am not sure if this command is useful though.
*** TODO Full-text search
:PROPERTIES:
:CREATED_TIME: [2018-08-24 Fri 15:26]
:ID:       2667c671-0e0b-405e-9924-7a9c9f6811d5
:END:
**** Deadgrep
In mastodon, Kaushal Modi mentioned deadgrep, which is a ripgrep frontend for Emacs. 

Deadgrep also provides a comparison between [[https://github.com/Wilfred/deadgrep/blob/master/docs/ALTERNATIVES.md][alternatives]] to the tool itself. 
**** Prefer rg over ag
I have used =counsel-ag=, but I will switch to =counsel-rg=. 

*** TODO Web search
:PROPERTIES:
:CREATED_TIME: [2018-08-17 Fri 08:46]
:ID:       81c5b1b2-f848-4a41-be21-4dba968484a7
:END:
- [[file:misc/init-web-search.el::(defun%20akirak/helm-search%20(query)][akirak/helm-search]] command lets you choose a search engine for a given query.
  - This command is bound at ~<menu> ?~ key.
  - This command is also available as an alternative action in =counsel-org-capture-string=.

[[file:misc/init-web-search.el][file:~/.emacs.d/misc/init-web-search.el]]

- [ ] Redefine search engine commands in terms of the new search engine scheme in =akirak/define-search-engine=

** Editing org-mode
*** Graphics and images in Org Mode
:PROPERTIES:
:ID:       d5035d86-4f0f-4e3d-907f-234c117b0061
:END:
**** TODO Adding screenshots
Maybe I will use org-download or some other solution.
**** TODO Generate diagrams using org-babel
- GraphViz
- Ditaa
- PlantUML
- etc.

** Using pandoc for document conversion
:PROPERTIES:
:ID:       a9cdcd00-68a0-4320-9236-c959a8370ed2
:END:
[[http://pandoc.org/][Pandoc]] is a document converter that supports a wide range of markup formats. As Org is one of its supported exporting formats, you can use pandoc to import documents from several documents to org.
** Japanese support through Katawa
:PROPERTIES:
:ID:       5e04241c-6428-4dbc-8983-6691e02a9104
:END:
:LOGBOOK:
- State "REVIEW"     from "NEXT"       [2018-07-08 Sun 19:44]
CLOCK: [2018-07-08 Sun 18:55]--[2018-07-08 Sun 19:14] =>  0:19
:END:
Because Japanese is my native language, I still have to rely on it for extensive vocabulary. [[file:international/init-katawa.el][katawa.el]] provides limited support for Japanese in a platform-independent manner.

Especially, =katawa-ivy= command is a convenient interface for Japanese. Rather than being a real input method, it can insert a small portion of Japanese text into the buffer without dependencies. Additional actions are configured in [[file:international/init-katawa.el::(ivy-add-actions%20'katawa-ivy][init-katawa.el]].
* Issues
:PROPERTIES:
:TOC:      1
:CUSTOM_ID: issues
:END:
** MAYBE Strip dependency on Dropbox                                 :MAYBE:
:PROPERTIES:
:CREATED_TIME: [2018-08-22 Wed 14:13]
:ID:       d2584edc-286d-4b2e-a374-22818f957c94
:END:
:LOGBOOK:
- State "MAYBE"      from "TODO"       [2018-08-22 Wed 14:14] \\
  I am not sure if this idea is good. It might be a good idea to keep a copy of those files in the cloud.
:END:
My configuration currently [[file:local/my-dropbox.el][depends on Dropbox]], which is bad as I am using syncthing as well to synchronise files between computers. 
** Bookmarks
:PROPERTIES:
:CREATED_TIME: [2018-09-01 Sat 09:07]
:ID:       67a6ed2d-b8fc-4958-b186-20369ab5dc00
:END:
- By default, the default bookmark file is ~/.emacs-bookmarks: [[file:core/init-defaults.el::(setq%20bookmark-default-file%20"~/.emacs-bookmarks")][init-defaults.el]].
  - It does not reside in ~/.emacs.d/.cache, because the directory can be purged for clearing local data, e.g. packages.
- When init-local.el (my personal configuration) is loaded and ~/learning/ exists, it is ~/learning/emacs-bookmarks. This is configured in my-org repository.
  - ~/learning is a Git repository, so the file is under version control. Adding a bookmark can be considered as part of a learning process, so every addition to a bookmark should be cared by the user.
* Deprecated
:PROPERTIES:
:TOC:      ignore
:END:
* Footnotes
:PROPERTIES:
:TOC:      ignore
:END:

# Local Variables:
# org-make-toc: t
# End:
