#+title: Emacs
* Overview of the configuration
** Menu key for help                            :help:keybinding:microhabit:
Use ~<menu>~ key as a prefix for alternative help commands. Especially, the following kinds of commands should bound on this prefix:

- Help/referencing commands specific to modes of the current buffer.
- Dictionary commands (for natural languages).

There is already ~<f1>~ (or ~C-h~ by default) for help commands, but these are about Emacs. If you want to get a context-specific help, try ~<menu>~.

*** Tutorial hydra                       :microhabit:keybinding:help:hydra:
By convention, ~<menu> h~ should be bound to a Hydra command for the major mode.
** Projectile and remote repositories
:PROPERTIES:
:ID:       96328360-8a53-47d6-afbb-d7b90aaea751
:END:
*** Use =helm-repom= to open a repository
I used =counsel-projectile-switch-project= for opening a local repository, but now that I have =repom=, I will use =helm-repom= to open a repository. If a repository is not available locally, then I can clone it from a remote server quickly.

- [[file:misc/init-repom.el]]
*** TODO Cleaning up the list
I have to maintain =projectile-known-projects= regularly:

- [X] Delete duplicates
- [X] Delete projects that no longer exists
- [ ] For repositories in some locations (e.g. straight packages), they should be deleted from the list unless they are in a dirty state

These tasks are completed by =projectile-cleanup-known-projects=. I have to run it regularly.

* Usage tips
** Scratch buffers                                              :microhabit:
Use scratch buffer extensively: [[file:coding/init-scratch.el]]
** hl-todo
[[https://github.com/tarsius/hl-todo][hl-todo]] package highlights todo keywords in buffers: [[file:coding/init-hl-todo.el::(use-package%20hl-todo][init-hl-todo.el]]
*** TODO Navigate through a buffer by todo keywords            :keybinding:
Bind keys to the following commands:

- [ ] =hl-todo-next/previous= commands
- [ ] =hl-todo-occur= command
*** magit-todos
[[file:apps/init-magit.el::(use-package%20magit-todos][magit-todos]] enhances =magit-status= to show todo items in files in the project.
* Issues
* Deprecated
* Footnotes
