# -*- mode: org; mode: org-make-toc; org-id-link-to-org-use-id: nil

* My Emacs Configuration
This is not a true literate configuration. Packages that demand complex configuration are configured in separate files. I am rewriting this configuration 
for a better understanding of my previous work and organizing it in a more sensible way.
** Table of contents                                              :noexport:
:PROPERTIES:
:TOC:      siblings
:END:
    -  [[#why][Why?]]
      -  [[#literate-configuration-in-org-mode][Literate configuration in Org mode]]
        -  [[#pros][Pros]]
        -  [[#cons][Cons]]
      -  [[#organizational-policies][Organizational policies]]
    -  [[#support-older-versions-of-emacs][Support older versions of Emacs]]
    -  [[#before-using-use-package][Before using use-package]]
    -  [[#overriding-defaults][Overriding defaults]]
    -  [[#keybindings-infrastructure][Keybindings infrastructure]]
      -  [[#repeatable-keys][Repeatable keys]]
      -  [[#per-mode-hydra][Per-mode hydra]]
      -  [[#generic-definer][Generic definer]]
      -  [[#definers-for-emacs-standard-prefix-keys][Definers for Emacs standard prefix keys]]
      -  [[#definers-for-non-standard-prefix-keys][Definers for non-standard prefix keys]]
    -  [[#dependencies-for-other-packages][Dependencies for other packages]]
      -  [[#dashel][dash.el]]
      -  [[#ivy][Ivy]]
      -  [[#helm][Helm]]
      -  [[#org][Org]]
      -  [[#hydra][Hydra]]
      -  [[#ov-overlays][ov (overlays)]]
      -  [[#ts-date-time-library-by-alphapapa][ts (date-time library by alphapapa)]]
      -  [[#all-the-icons][all-the-icons]]
      -  [[#emacsql-sqlite][emacsql-sqlite]]
    -  [[#appearances][Appearances]]
      -  [[#theme][Theme]]
      -  [[#frame-elements][Frame elements]]
      -  [[#typography][Typography]]
        -  [[#how-to-install-fonts][How to install fonts]]
    -  [[#a-bunch-of-useful-features][A bunch of useful features]]
      -  [[#frame-workflow][frame-workflow]]
      -  [[#terminal][Terminal]]
      -  [[#dired][Dired]]
      -  [[#magit][Magit]]
      -  [[#forge][Forge]]
      -  [[#chrome][Chrome]]
      -  [[#yasnippet-and-auto-yasnippet][Yasnippet and auto-yasnippet]]
      -  [[#avy][Avy]]
      -  [[#source-code-navigation][Source code navigation]]
      -  [[#outline-navigation][Outline navigation]]
      -  [[#outline-editing][Outline editing]]
      -  [[#referencing][Referencing]]
      -  [[#miscellaneous-commands][Miscellaneous commands]]
      -  [[#poporg][Poporg]]
      -  [[#hydra-for-windows][Hydra for windows]]
      -  [[#visual-cues-and-extra-information-display][Visual cues and extra information display]]
      -  [[#lacarte][LaCarte]]
      -  [[#dsls][DSLs]]
      -  [[#startup-windows][Startup window(s)]]
      -  [[#auto-saving-and-auto-git-commit][Auto saving and auto git-commit]]
      -  [[#org-web-tools-and-clipurl][org-web-tools and clipurl]]
    -  [[#writing][Writing]]
      -  [[#hydra-for-org-mode][Hydra for Org-mode]]
      -  [[#graphviz][GraphViz]]
      -  [[#ditaa][Ditaa]]
      -  [[#exporting][Exporting]]
      -  [[#markdown][Markdown]]
    -  [[#programming-languages][Programming languages]]
      -  [[#emacs-lisp][Emacs Lisp]]
      -  [[#elixir][Elixir]]
      -  [[#haskell][Haskell]]
      -  [[#shell-scripts-bash][Shell scripts (bash)]]
      -  [[#elm][Elm]]
      -  [[#kotlin][Kotlin]]
      -  [[#nim][Nim]]
      -  [[#python][Python]]
      -  [[#rust][Rust]]
    -  [[#emacs-applications][Emacs applications]]
      -  [[#getting-organised][Getting organised]]
        -  [[#jump-to-the-current-context][Jump to the current context]]
        -  [[#frame][Frame]]
        -  [[#org-agenda-keybindings][Org-agenda keybindings]]
      -  [[#beancount][Beancount]]
    -  [[#meta][Meta]]
      -  [[#import-from-the-previous-configuration][Import from the previous configuration]]

** Why?
*** Literate configuration in Org mode
Quite a few people maintain their Emacs configuration in a single literate Org file. I didn't like the idea, but I have to admit that it offers several benefits.
**** Pros
- You can quickly add a piece of configuration by refiling a subtree to the file from another location, e.g. your inbox Org file.
- You'll be exposed to a constant pressure to maintain a consistent structure, so the configuration will be more consistent.
- Each piece of configuration gets an explicit context.
**** Cons
- It is slightly more tedious to edit the literate config in Org mode. Rather than edit a file directly, you have to pop up an edit buffer for each piece of configuration you want to change.
- Revision history is lost when entries are reordered. This can be prevented by automatically sorting all headings before saving.
*** Organizational policies
I will combine both a literate configuration file and separate configuration files:

- The main configuration file is a single Org file containing babel source blocks. Simple package configurations can be put directly in the file.
- Complex package configurations are put in separate files, because they are likely to entail bugfixes and updates.
- However, certain kinds of configuration code to integrate those packages can be put in the Org configuration file. Keybindings and frame (frame-workflow) configurations are examples of such ones. They are inherently personal and often interrelated, so it doesn't make sense to treat them as independent ideas.

In principle, the main configuration file should be a thin layer of the Emacs configuration, even though they can contain some complex pieces.
** Support older versions of Emacs
=when-let= and =if-let= are available in Emacs 25.1, but they have been renamed to =when-let*= and =if-let*= in 26.1, which are correct names to describe their behaviours.

#+begin_src emacs-lisp
  (eval-and-compile
    (when (version< emacs-version "26")
      (with-no-warnings
        (defalias 'when-let* #'when-let)
        (function-put #'when-let* 'lisp-indent-function 1)
        (defalias 'if-let* #'if-let)
        (function-put #'if-let* 'lisp-indent-function 2))))
#+end_src

** Before using =use-package=
These packages are required in other use-package directives declared in this
configuration.

Save efforts to configure individual variable files using no-littering

#+begin_src emacs-lisp
(use-package no-littering
  :init
  (setq no-littering-var-directory
        (expand-file-name ".cache" user-emacs-directory)))
#+end_src

Use the executable path from the shell

#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :if (memq window-system '(mac ns x))
  :init
  (exec-path-from-shell-initialize))
#+end_src

Use diminish to reduce clutters from the modeline. This adds support for =:diminish= keyword:

#+begin_src emacs-lisp
  (use-package diminish
    :disabled t
    :init
    (diminish 'auto-revert-mode)
    (diminish 'outline-minor-mode)
    (diminish 'flyspell-mode))
#+end_src

Deprecated: Allow installation of system packages via use-package

#+begin_src emacs-lisp
  (use-package system-packages)

  (use-package use-package-ensure-system-package)
#+end_src

** Overriding defaults
These settings don't depend on external dependencies, so they should be applied earlier.

#+begin_src emacs-lisp
  (akirak/require 'setup-defaults t)
#+end_src

** Keybindings infrastructure
Use general.el to define keybindings. It has made several improvements over
bind-key, including a built-in support for which-key.

#+begin_src emacs-lisp
  (use-package general)
#+end_src

This also adds support for =:general= keyword in use-package directives

Allow use of =:wk= keyword in general.el keybinding definitions

#+begin_src emacs-lisp
  (akirak/require 'setup-which-key t)
#+end_src

*** Repeatable keys

Hopefully, defrepeater is soon going to be integrated with general

#+begin_src emacs-lisp
  (akirak/require 'setup-defrepeater t)
#+end_src

*** Per-mode hydra
As it is hard to remember workflow for every programming language, I've decided to set up a hydra for each programming language I use. Frequently-used commands specific to a major mode should be added to the hydra for its language. All mode hydras should share the same keybinding, which is currently ~C-d~.

I added a function =akirak/bind-mode-hydra= which binds a per-mode hydra for on the key. It takes the name of the major mode and binds the key to =akirak/MODE-hydra/body=. This is not a precisely keybinding definer but plays a somewhat similar role.

#+begin_src emacs-lisp
  (defcustom akirak/mode-hydra-key (kbd "C-c d")
    "Key sequence to access the hydra for the current mode.")

  (defun akirak/bind-mode-hydra (mode &optional hydra-function)
    (let ((map (intern (concat (symbol-name mode) "-map"))))
      (define-key (symbol-value map) akirak/mode-hydra-key
        (or hydra-function
            (intern (format "akirak/%s-hydra/body" mode))))))
#+end_src
*** Generic definer
#+begin_src emacs-lisp
  (general-create-definer akirak/bind-key)
#+end_src
*** Definers for Emacs standard prefix keys
**** M-s: Search
#+begin_src emacs-lisp
  (general-create-definer akirak/bind-search :prefix "M-s")
  (define-obsolete-function-alias 'akirak/bind-search-map
    'akirak/bind-search)
#+end_src
**** M-g: Jump
#+begin_src emacs-lisp
  (general-create-definer akirak/bind-jump :prefix "M-g")
#+end_src
**** M-r: Registers
#+begin_src emacs-lisp
  (general-def
    "M-r" (general-simulate-key "C-x r"))
#+end_src

#+begin_src emacs-lisp
  (general-create-definer akirak/bind-register :prefix "C-x r")
  (define-obsolete-function-alias 'akirak/bind-register-map
    'akirak/bind-register)
#+end_src

#+begin_src emacs-lisp
  (akirak/bind-register "M-r" #'ivy-resume)
#+end_src
**** F1: Help
#+begin_src emacs-lisp
  (general-create-definer akirak/bind-help :prefix "<f1>")
#+end_src
*** Definers for non-standard prefix keys
I often need to tweak Emacs while I am using it.

#+begin_src emacs-lisp
  (general-create-definer akirak/bind-customization :prefix "C-x c")

  (define-obsolete-function-alias 'akirak/bind-customize-map
    'akirak/bind-customization)
#+end_src

There are not so many commands that need to be add to the map:

#+begin_src emacs-lisp
  (akirak/bind-customization
    "" '(nil :wk "customize")
    "f" #'customize-face-other-window
    "g" #'customize-group-other-window
    "l" #'load-library
    "p" '((lambda () (interactive)
            (if (featurep 'straight)
                (call-interactively 'straight-use-package)
              (package-list-packages)))
          :wk "packages")
    "s" #'customize-set-value
    "v" #'customize-variable-other-window)
#+end_src

~C-c~ is reserved for the user:

#+begin_src emacs-lisp
  (general-create-definer akirak/bind-user :prefix "C-c")
#+end_src

Add a prefix for keybindings to eval commands:

#+begin_src emacs-lisp
  (general-create-definer akirak/bind-eval :prefix "C-c e")
  (define-obsolete-function-alias 'akirak/bind-eval-map 'akirak/bind-eval)
#+end_src

Generic prefix key for editing commands:

#+begin_src emacs-lisp
(general-create-definer akirak/bind-generic :prefix "C-.")
#+end_src

#+begin_src emacs-lisp
(akirak/bind-generic
  "j" #'katawa-ivy-fix-at-point
  "o" #'split-line ; Originally C-M-o
  "SPC" 'just-one-space)
#+end_src

Prefix for mode-specific keys:

#+begin_src emacs-lisp
(defconst akirak/mode-prefix-key "C-,")
(general-create-definer akirak/bind-mode :prefix akirak/mode-prefix-key)
#+end_src

#+begin_src emacs-lisp
  (general-create-definer akirak/bind-extra-help :prefix "<f1>x")
#+end_src

#+begin_src emacs-lisp
  (akirak/bind-extra-help
    "c" #'describe-char
    "f" #'counsel-describe-face)
#+end_src

** Dependencies for other packages
:PROPERTIES:
:TOC:      1
:CUSTOM_ID: dependencies
:ID:       ee01d40d-51af-4598-825e-dc79e4e0c394
:END:
These packages may be required by other packages loaded later on.
*** dash.el
Quite a few packages depend on =dash.el= and/or =dash-functional.el=, so they should be loaded in the very beginning of package declarations.

#+begin_src emacs-lisp
  (use-package dash)
  (use-package dash-functional)
#+end_src
*** Ivy
#+begin_src emacs-lisp
  (akirak/require 'setup-ivy t)
#+end_src
*** Helm
#+begin_src emacs-lisp
  (akirak/require 'setup-helm t)
#+end_src
*** Org
**** Org-babel
#+begin_src emacs-lisp
  (akirak/require 'setup-org-babel t)
#+end_src
To add support for a language in org-babel, add the following configuration:

- Add =(LANG . t)= to =org-babel-load-languages= in =:init= section of a =use-package= directive.
- If necessary, add a custom mapping to =org-src-lang-modes=.
****  Org-export
Some exporters, e.g. =ox-hugo=, depend on =ox-org=, and it is tedious to add =(require 'ox-org)= to all of their configurations, so I will load it immediately after =ox= is loaded.

#+begin_src emacs-lisp
  (use-package ox
    :after org
    :straight nil
    :config
    ;; Workaround for preventing a loading error in some exporter packages
    (require 'ox-org))
#+end_src

*** Hydra
#+begin_src emacs-lisp
(use-package hydra)
#+end_src
*** ov (overlays)
#+begin_src emacs-lisp
(use-package ov
  :straight (ov :host github :repo "ShingoFukuyama/ov.el"))
#+end_src
*** ts (date-time library by alphapapa)
#+begin_src emacs-lisp
  (use-package ts
    :straight (ts :host github :repo "alphapapa/ts.el"))
#+end_src
*** all-the-icons
#+begin_src emacs-lisp
(use-package all-the-icons)
#+end_src
*** emacsql-sqlite
#+begin_src emacs-lisp
  (use-package emacsql-sqlite
    :disabled t
    :init
    (let ((default-directory "~/.emacs.d/straight/repos/emacsql"))
      (if (file-exists-p "emacsql-sqlite.elc")
          (message "emacsql-sqlite has been already built")
        (compile "make sqlite/emacsql-sqlite")
        (compile "make emacsql-sqlite.elc"))))
#+end_src
** Appearances
*** Theme
I have been using dracula, but I may switch to another theme with light background.

#+begin_src emacs-lisp
  (akirak/require 'setup-dracula-theme t)
#+end_src

*** Frame elements
Due to consistency with other applications on computer, my eyes tend to stay in the upper area of a window. I prefer relying on the header line extensively rather than the modeline.

#+begin_src emacs-lisp
  (akirak/require 'setup-header-line t) ; Hide the mode line and use the header line
  (akirak/require 'setup-feebleline t)  ; Display extra information in the echo area
  (akirak/require 'setup-frame-title t) ; Configure a custom frame title format
#+end_src
*** Typography
This modules configures extra face attributes for typography. 
This feature is enabled if and only if a window system is
available.

#+begin_src emacs-lisp
  (when (window-system)
    (akirak/require 'setup-typography))
#+end_src
**** TODO How to install fonts
The typography module depends on several fonts from many packages. I have to document how to install them.
** A bunch of useful features
:PROPERTIES:
:TOC:      1
:ID:       7042f1a9-0cd3-4769-acda-a98d200f569b
:CUSTOM_ID: enhancements
:END:
#+begin_src emacs-lisp
  (dolist (feature '(setup-shell-bindings ; Make ~C-a~, ~C-w~,  ~C-h~, etc. behave like in shells
                     setup-key-translation ; Translate certain key combinations for ergonomics
                     setup-keybindings     ; My global keybindings
                     setup-counsel         ; Basic Counsel commands
                     setup-projectile      ; Manage projects
                     setup-swiper ; Incremental search through the buffer using Ivy
                     setup-aggressive-indent
                     setup-lispy          ; Efficient lisp editing
                     setup-ivy-filthy-rich ; Provide more information via Ivy/Counsel commands
                     setup-ivy-frame-actions ; Add frame-creation actions to Ivy
                     setup-magit       ; The Git porcelain for Emacs
                     setup-helpful     ; Extended helpful commands
                     setup-company     ; Auto completion
                     setup-eldoc       ; Display short help while coding
                     setup-dired       ; File browser
                     setup-multi-term  ; Terminal emulator
                     setup-aweshell    ; Enhance eshell
                     setup-rename      ; Utilities for rename operations
                     setup-crux ; Collection of utilities with modifications
                     setup-google-translate ; Translate a word in a buffer
                     ;; setup-japanese
                     setup-helm-descbinds ; Better keybinding search
                     setup-helm-make  ; Choose a make command via Helm
                     setup-anzu       ; Provide info in search & replace
                     setup-smartparens   ; Parenthesis editing
                     setup-org-make-toc  ; Generating TOCs
                     setup-unpackaged    ; A bunch of useful commands
                     setup-locate        ; Configure locate and updatedb
                     setup-org-custom-commands
                     setup-ace-window ; An alternative way for window manipulation
                     setup-yasnippet  ; Snippets for programming
                     setup-yankpad
                     setup-sidebar   ; ibuffer and dired sidebars
                     setup-outshine  ; Extra support for outline editing
                     setup-init-time-log  ; Log init time
                     setup-autoinsert     ; File templates
                     setup-org-capture    ; Org-capture templates
                     setup-org-starter    ; Org starter
                     setup-counsel-org-capture-string
                     setup-org-refile     ; Enhance org-refile
                     setup-org-download   ; Screenshots
                     setup-org-mind-map
                     setup-link-hint      ; Jumping to a URL
                     setup-helm-org-rifle
                     setup-lsp            ; Language-agnostic IDE toolkit
                     setup-japanese
                     setup-rich-minority  ; Whitelist minor modes
                     setup-clipboard      ; Clipboard integration
                     setup-ivy-omni-org
                     setup-bm
                     ))
    (akirak/require feature))
#+end_src

The following packages are enhancements to Emacs that don't require much configuration:

#+begin_src emacs-lisp
  (use-package smex) ; Install smex for sorting M-x candidates
  (use-package savehist)                  ; Save minibuffer history
  (use-package helm-system-packages :after helm ; Install system packages
    :commands (helm-system-packages))
  (use-package helm-systemd :after helm   ; Run (root) systemd operations
    :commands (helm-systemd))
  (use-package hl-todo
    :hook (prog-mode . hl-todo-mode))
  (use-package fwb-cmds
    :straight (fwb-cmds :host github :repo "tarsius/fwb-cmds"))
  (use-package helm-tail :after helm
    :straight (helm-tail :host github :repo "akirak/helm-tail")
    :commands (helm-tail))
  (use-package counsel-projectile
    :after (projectile counsel)
    :init
    (counsel-projectile-mode 1))
  (use-package olivetti                   ; Distraction-free editing
    :commands (turn-on-olivetti-mode)
    :custom (olivetti-body-width 92))
  (use-package fontify-face
    :hook
    (emacs-lisp . (lambda () (fontify-face-mode 1))))
  (use-package rainbow-mode
    ;; :diminish 'rainbow-mode
    :commands (rainbow-mode)
    :hook
    (prog-mode . (lambda () (rainbow-mode 1))))
  (use-package docker)                    ; Manage docker services
  (use-package prodigy)                   ; Manage daemons
  (use-package helm-linux-disks
    :straight (helm-linux-disks :host github
                                :repo "akirak/helm-linux-disks")
    :commands (helm-linux-disks)
    :custom
    (linux-disk-terminal-type 'akirak/shell-new))
  (use-package esup                       ; Profile the startup process
    :commands (esup))
  (use-package git-modes)
  (use-package fix-word
    :commands (fix-word-upcase fix-word-downcase fix-word-capitalize)
    :general
    ([remap upcase-word] 'fix-word-upcase
     [remap downcase-word] 'fix-word-downcase
     [remap capitalize-word] 'fix-word-capitalize))
  (use-package scratch
    :commands (scratch))
  (use-package embrace
    ;; I probably don't need this package. Use sp-{rewrap,unwrap}-sexp
    ;; instead
    :disabled t)
  (use-package dumb-jump
    ;; Don't enable dumb-jump-mode. Bind only necessary commands. 
    :custom
    (dumb-jump-selector 'ivy))
  (use-package iedit
    :general
    ("C-;" 'iedit-mode))
  (use-package comment-dwim-2
    :general
    ("M-;" 'comment-dwim-2))
  (autoload 'narrow-or-widen-dwim "narrow-or-widen.el")
  (use-package counsel-org-clock)
  (use-package org-reverse-datetree
    :straight (org-reverse-datetree :host github
                                    :repo "akirak/org-reverse-datetree"))
  (use-package org-autolist ; Edit Org-Mode lists like in word processors
    :after org
    ;; :diminish 'org-autolist-mode
    :init
    (add-hook 'org-mode-hook #'org-autolist-mode))
  (use-package org-bookmark-heading ; Allow you to bookmark headings in Org-Mode
    :after org)
  (use-package org-bullets :after org
    :init
    (add-hook 'org-mode-hook 'org-bullets-mode))
  (use-package org-mind-map               ; Exporting mind maps
    :after (org ox))
#+end_src

*** frame-workflow
[[https://github.com/akirak/frame-workflow][frame-workflow]] is my package originally written for providing named workspaces in EXWM. 

#+begin_src emacs-lisp
  (akirak/require 'setup-frame-workflow t) ; Ensure loading frame-workflow

  (general-def "C-M-g" #'frame-workflow-prefix-map)
#+end_src

*** Terminal
#+begin_src emacs-lisp
  (akirak/require 'setup-terminal t)
#+end_src
**** Frame

#+begin_src emacs-lisp
  (akirak/define-frame-workflow "terminal"
    :key "t"
    :make-frame
    '(frame-purpose-make-frame :modes '(term-mode
                                        eshell-mode
                                        shell-mode))
    :layout
    '(ibuffer-sidebar-show-sidebar))
#+end_src

*** Dired
#+begin_src emacs-lisp
  (general-def "C-x C-j" #'dired-jump)
#+end_src
**** Hydra
#+begin_src emacs-lisp
  (defhydra akirak/dired-mode-hydra ()
    ""
    ("r" dired-rsync))

  (akirak/bind-mode-hydra 'dired-mode)
#+end_src
**** Frame
#+begin_src emacs-lisp
  (akirak/define-frame-workflow "dired"
    :key "d"
    :make-frame
    '(frame-purpose-make-mode-frame 'dired-mode)
    :layout
    '(when (fboundp 'ibuffer-sidebar-show-sidebar)
       (ibuffer-sidebar-show-sidebar)))
#+end_src

*** Crux and file operations
#+begin_src emacs-lisp
  (general-def
    "C-x D" #'crux-delete-file-and-buffer
    "C-x R" #'crux-rename-file-and-buffer
    "C-x S" #'sudo-find-file
    "C-x x" #'crux-open-with)
#+end_src
*** Magit
The following packages extend the display of =magit-status=:

- magit-todos
- magithub
**** magit-todos
#+begin_src emacs-lisp
  (use-package magit-todos :after (magit hl-todo)
    :straight (magit-todos :host github :repo "alphapapa/magit-todos")
    :config
    (magit-todos-mode 1))
#+end_src
**** magithub
As magithub slows down magit-status, it sometimes causes problems,
and I don't always need its features, I will disable it by default.
I will load =setup-magithub= library if I need it.
**** Forge
#+begin_src emacs-lisp
  (use-package forge
    ;; Depends on emacsql-sqlite
    :disabled t
    :straight (forge :host github :repo "magit/forge"))
#+end_src
*** Chrome
#+begin_src emacs-lisp
(use-package atomic-chrome
  :disabled t
  :init
  (atomic-chrome-start-server))
#+end_src
*** Company completion
#+begin_src emacs-lisp
(general-def :package 'company :keymaps 'company-mode-map
  "M-/" #'company-complete)
#+end_src
*** Yasnippet and auto-yasnippet

I prefer using =ivy-yasnippet= for choosing a snippet:

#+begin_src emacs-lisp
  (akirak/bind-user "y" 'ivy-yasnippet)
#+end_src

=auto-yasnippet= is convenient for temporary snippets:

#+begin_src emacs-lisp
  (akirak/bind-register-map
    "a" 'aya-create
    "e" 'aya-expand)
#+end_src

=aya-open-line= is the fastest way to expand a snippet if you know its name. It behaves like =open-line= if the word before the point is not registered as a snippet:

#+begin_src emacs-lisp
  (general-def "C-o" 'aya-open-line)
#+end_src

Yankpad is more useful in writing, so bind a key to =yankpad-insert=:

#+begin_src emacs-lisp
  (akirak/bind-user "p" 'akirak/yankpad-insert)
#+end_src
*** Frequent counsel commands                                  :navigation:
#+begin_src emacs-lisp
  (general-def
    "C-x p" #'counsel-projectile
    "C-x /" #'counsel-rg
    "C-x F" #'counsel-recentf
    "C-x L" #'counsel-locate)
#+end_src
*** Avy                                                        :navigation:
#+begin_src emacs-lisp
  (akirak/bind-key "C-'" 'avy-goto-char-timer)

  (general-unbind "C-'" :keymaps 'org-mode-map :package 'org)
#+end_src

=link-hint= is not part of =avy= package, but it is covenient for following a link:

#+begin_src emacs-lisp
  (akirak/bind-jump "f" 'akirak/link-hint-open-link)
#+end_src
*** Source code navigation                                     :navigation:

#+begin_src emacs-lisp
  (akirak/bind-jump
    "." #'dumb-jump-go
    "," #'dumb-jump-back)
#+end_src

#+begin_src emacs-lisp
  (akirak/bind-search "i" 'counsel-imenu)

  (akirak/bind-search :package 'org :keymaps 'org-mode-map
    "i" 'counsel-org-goto)
#+end_src

*** Outline navigation                                         :navigation:
#+begin_src emacs-lisp
  (akirak/bind-jump :package 'outline :keymaps 'outline-minor-mode-map
    "h" 'outline-up-heading)

  (akirak/bind-jump  :package 'org :keymaps 'org-mode-map
    "h" 'org-up-element)
#+end_src

#+begin_src emacs-lisp
  (akirak/bind-search "o" 'counsel-outline)
  (akirak/bind-search :package 'org :keymaps 'org-mode-map
    "o" 'counsel-org-goto)
#+end_src

*** Outline editing                                              :outlines:
#+begin_src emacs-lisp
  (general-def :keymaps 'outline-minor-mode-map :package 'outshine
    "M-RET" 'outshine-insert-heading)
  (general-unbind :keymaps 'lispy-mode-map :package 'lispy "M-RET")
#+end_src
*** Referencing                                               :referencing:
#+begin_src emacs-lisp
  (akirak/bind-search
    "d" #'helm-dash)

  ;; "a" #'helm-dash-activate-docset
  ;; "d" #'helm-dash-at-point
  ;; "+" #'helm-dash-install-docset
#+end_src

#+begin_src emacs-lisp
  (akirak/bind-help "M" #'woman)
#+end_src
*** Miscellaneous commands
**** Switching to an Org window
#+begin_src emacs-lisp
  (defvar org-select-window-last-window nil)

  (defun org-select-window (arg)
    (interactive "P")
    (if arg
        (progn
          (when org-select-window-last-window
            (select-window org-select-window-last-window)
            (setq org-select-window-last-window nil)))
      (let* ((wlist (window-list))
             (i0 (-elem-index (selected-window) wlist))
             (queue (append (-slice wlist (1+ i0))
                            (-take i0 wlist)))
             (w (-find (lambda (w)
                         (with-current-buffer (window-buffer w)
                           (derived-mode-p 'org-mode)))
                       queue)))
        (if w
            (progn
              (unless (derived-mode-p 'org-mode)
                (setq org-select-window-last-window (selected-window)))
              (select-window w))
          (message "No other org window in this frame")))))
#+end_src
**** modi/org-split-block
#+begin_src emacs-lisp
  (akirak/require 'modi-org-split-block)
  (akirak/bind-key :package 'org :keymaps 'org-mode-map
    [remap org-meta-return] 'modi/org-meta-return)
#+end_src
*** Poporg
:PROPERTIES:
:CREATED_TIME: [2018-12-29 Sat 19:51]
:ID:       e76069bd-d9b2-488a-a5c8-9f2410240396
:END:

Use poporg rather than outorg.

- [X] Add poporg package
- [X] Remap keys

#+begin_src emacs-lisp
  (use-package poporg)
  (akirak/bind-user "'" 'poporg-dwim)
  ;; The default keybindings in poporg-mode-map are not intuitive to me,
  (akirak/bind-key :keymaps 'poporg-mode-map
    "C-c C-c" 'poporg-edit-exit
    "C-x C-s" 'poporg-update-and-save)
#+end_src
*** Hydra for windows
:PROPERTIES:
:CREATED_TIME: [2018-12-31 Mon 05:04]
:END:
I created a hydra for managing frames and windows.

#+begin_src emacs-lisp
  (akirak/require 'setup-window-hydra)
  (akirak/bind-key "M-o" #'akirak/window-hydra/body)
  (general-unbind :keymaps 'lispy-mode-map :package 'lispy "M-o")
#+end_src
*** Visual cues and extra information display

Additional visual cues can increase productivity, but they can be noisy at the same time. Therefore I need to justify each package added to my config.

**** Beacon
I often lose sight of the cursor when I switch to another window, so this is necessary.
#+begin_src emacs-lisp
  (use-package beacon                     ; Highlight the cursor on certain events
    :config
    (beacon-mode 1))
#+end_src
**** Rainbow-delimiters
This is especially useful in editing Lisp code.
#+begin_src emacs-lisp
(use-package rainbow-delimiters         ; Colourize parentheses in source code
  :hook
  (prog-mode-hook . rainbow-delimiters-mode))
#+end_src
**** Dimmer
This package makes the focused window stands out by dimming the other windows. However, the dimness should be kept small to make referenced text readable.
#+begin_src emacs-lisp
  (akirak/require 'setup-dimmer)
#+end_src
**** Git-gutter
This lets you know which parts of the buffers are modified since the last commit.
#+begin_src emacs-lisp
  (use-package git-gutter
    :diminish git-gutter-mode
    :init
    (global-git-gutter-mode))
#+end_src
**** Highlight-indent-guides
This is helpful in programming languages that depend on indentation levels.
#+begin_src emacs-lisp
  (use-package highlight-indent-guides
    :init
    (add-hook 'prog-mode-hook 'highlight-indent-guides-mode))
#+end_src
**** Fill-column-indicator
Visualise (usually) 80 columns.
#+begin_src emacs-lisp
  (use-package fill-column-indicator
    :init
    (add-hook 'prog-mode-hook 'fci-mode))
#+end_src
**** Whitespace
Visualise unnecessary, extra whitespace characters in source code.
#+begin_src emacs-lisp
  (use-package whitespace
    :straight nil
    :diminish whitespace-mode
    :hook
    (prog-mode-hook . whitespace-mode)
    :custom
    (whitespace-display-mappings
     ;; all numbers are Unicode codepoint in decimal. try (insert-char 182 ) to see it
     '(
       (space-mark 32 [183] [46]) ; 32 SPACE, 183 MIDDLE DOT 「·」, 46 FULL STOP 「.」
       (newline-mark 10 [182 10]) ; 10 LINE FEED
       (tab-mark 9 [187 9] [9655 9] [92 9]) ; 9 TAB, 9655 WHITE RIGHT-POINTING TRIANGLE 「▷」
       ))
    (whitespace-style '(face tabs trailing tab-mark)))
#+end_src

*** LaCarte
:PROPERTIES:
:CREATED_TIME: [2019-01-01 Tue 12:16]
:ID:       9f69a1f2-bc17-4dd1-b98e-51a398b0cb6e
:END:
:LOGBOOK:
CLOCK: [2019-01-01 Tue 12:16]--[2019-01-01 Tue 12:18] =>  0:02
:END:

Emacs seems to have a problem with popups on Chrome OS. Now ~<f10>~ is a dangerous key by default, so I will remap the key to lacarte instead:

#+begin_src emacs-lisp
  (use-package lacarte
    :commands (lacarte-execute-menu-command))
  (akirak/bind-key [remap menu-bar-open] #'lacarte-execute-menu-command)
#+end_src
*** DSLs
**** Meson                                                 :build__system:

#+begin_src emacs-lisp
  (use-package meson-mode)
#+end_src
**** YAML                                        :configuration__language:

#+begin_src emacs-lisp
  (akirak/require 'setup-yaml)
#+end_src
***** Ansible
Ansible is based on YAML.

#+begin_src emacs-lisp
  ;; (akirak/require 'setup-ansible)
#+end_src
**** Dockerfile                                  :configuration__language:

#+begin_src emacs-lisp
  (akirak/require 'setup-dockerfile)
#+end_src
**** Nix                                         :configuration__language:
#+begin_src emacs-lisp
  (akirak/require 'setup-nix)
#+end_src
*** Startup window(s)
By default, =*Messages*= buffer is shown at startup. This behaviour can be altered by overriding =akirak/setup-startup-windows= function.
#+begin_src emacs-lisp
  ;;;; Startup window
  ;; Switch to *Messages* at startup
  (defun akirak/setup-startup-windows ()
    (switch-to-buffer "*Messages*"))

  (add-hook 'emacs-startup-hook 'akirak/setup-startup-windows)
#+end_src
*** Auto saving and auto git-commit

Files are automatically saved on certain events by =super-save-mode=:

#+begin_src emacs-lisp
  (akirak/require 'setup-super-save)
#+end_src

You can also configure automatic git-commit using =git-auto-commit-mode=, but this is not enabled by default:

#+begin_src emacs-lisp
  (use-package git-auto-commit-mode)
#+end_src
*** org-web-tools and clipurl
[[https://github.com/alphapapa/org-web-tools][org-web-tools]] is handy, but commands in the package often fail to retrieve a proper URL I want to operate on. Therefore I created =clipurl= package to pick a URL from the kill ring.

#+begin_src emacs-lisp
  (use-package org-web-tools)

  (use-package clipurl
    :straight (clipurl :host github :repo "akirak/clipurl.el"))

  (use-package ivy-clipurl
    :straight clipurl
    :commands (ivy-clipurl)
    :config
    (ivy-add-actions 'ivy-clipurl
                     '(("r" org-web-tools-read-url-as-org "Read as Org"))))

  (akirak/bind-user "w" 'ivy-clipurl)
#+end_src

*** Highlighting part(s) of source code
:PROPERTIES:
:CREATED_TIME: [2019-01-25 Fri 22:47]
:END:

- bm (visual bookmarks)
- symbol-overlay

#+begin_src emacs-lisp
(akirak/bind-user
  "b" 'helm-bm
  "m" 'bm-toggle
  "s" 'symbol-overlay-put)
#+end_src
** Writing
:PROPERTIES:
:TOC:      1
:END:
Set the basic options for org-mode:

#+begin_src emacs-lisp
  (akirak/require 'setup-org t)
#+end_src
*** Hydra for Org-mode
#+begin_src emacs-lisp
  (defhydra akirak/org-mode-hydra (:exit t :hint nil)
    "
  Org

  ^^Export
  ^^--------------
  _h_ hugo subtree

  _mb_ mindmap buffer
  _mt_ mindmap subtree
  "

    ("h" akirak/org-hugo-export-subtree)
    ("mb" org-mind-map-write)
    ("mt" org-mind-map-write-current-tree))

  (akirak/bind-mode-hydra 'org-mode)
#+end_src

*** GraphViz
#+begin_src emacs-lisp
  (use-package graphviz-dot-mode)

  (use-package ob-dot
    :after ob
    :straight nil
    :init
    (require 'ox-org)
    (add-to-list 'org-babel-load-languages '(dot . t))
    (add-to-list 'org-src-lang-modes '("dot" . graphviz-dot)))
#+end_src
*** Ditaa
#+begin_src emacs-lisp
  (use-package ob-ditaa
    :after ob
    :straight nil
    :init
    (add-to-list 'org-babel-load-languages '(ditaa . t)))
#+end_src
*** Exporting
**** ox-hugo
#+begin_src emacs-lisp
  (akirak/require 'setup-org-hugo)
#+end_src
*** Markdown
Markdown is supported as well:

#+begin_src emacs-lisp
  (akirak/require 'setup-markdown)
#+end_src

** Programming languages
:PROPERTIES:
:TOC:      1
:END:
Ideally, this section should be a portfolio of my skills.
*** Emacs Lisp
#+begin_src emacs-lisp
(akirak/require 'setup-emacs-lisp)
#+end_src
**** Hydra
#+begin_src emacs-lisp
  (defhydra akirak/emacs-lisp-mode-hydra (:exit t :hint nil)
    "
  emacs-lisp

  ^^Point/last sexp  ^^Buffer          ^^Help/doc
  ^^---------------  ^^--------------  ----------
  _._ helpful        _e_ eval          _i_ info symbol
  _m_ macroexp       _l_ package-lint  _s_ suggest

  "
    ("i" counsel-info-lookup-symbol)
    ("s" suggest)
    ("." helpful-at-point)
    ("e" akirak/eval-buffer-or-load-file)
    ("l" package-lint-current-buffer)
    ("m" pp-macroexpand-last-sexp)
    ("q" nil "quit"))

  (akirak/bind-mode-hydra 'emacs-lisp-mode)
#+end_src
**** Frame
#+begin_src emacs-lisp
  (akirak/define-frame-workflow "emacs-lisp"
    :key "e"
    :make-frame '(frame-purpose-make-mode-frame 'emacs-lisp-mode))
#+end_src
**** Frame for the Emacs config
#+begin_src emacs-lisp
  (akirak/define-frame-workflow "emacs-config"
    :key "C"
    :layout
    '(progn
       (delete-other-windows)
       (let ((default-directory user-emacs-directory))
         (frame-workflow-magit-same-window)))
    :make-frame
    '(frame-purpose-make-directory-frame user-emacs-directory))
#+end_src
**** EMake
#+begin_src emacs-lisp
  (akirak/require 'setup-emake)
#+end_src
*** Elixir

#+begin_src emacs-lisp
  (akirak/require 'setup-elixir)
#+end_src

*** Haskell

#+begin_src emacs-lisp
  (akirak/require 'setup-haskell)
#+end_src

*** Shell scripts (bash)

#+begin_src emacs-lisp
  (use-package company-shell
    :init
    (add-to-list 'company-backends 'company-shell))
#+end_src

*** Elm

#+begin_src emacs-lisp
  (akirak/require 'setup-elm)
#+end_src

*** Kotlin

#+begin_src emacs-lisp
  (akirak/require 'setup-kotlin)
#+end_src

*** Nim

#+begin_src emacs-lisp
  (akirak/require 'setup-nim)
#+end_src

*** Python

#+begin_src emacs-lisp
  (akirak/require 'setup-python)
#+end_src

*** Rust
:PROPERTIES:
:CREATED_TIME: [2019-01-01 Tue 15:54]
:ID:       e15d3e74-9760-4e6f-ba18-9cb337758247
:END:
:LOGBOOK:
CLOCK: [2019-01-01 Tue 15:54]--[2019-01-01 Tue 15:56] =>  0:02
:END:
#+begin_src emacs-lisp
  (use-package rust-mode)
#+end_src
** Emacs applications
*** Getting organised
**** Jump to the current context
Use =my-goto= function to locate the current context.

 #+begin_src emacs-lisp
   (defcustom my-goto-default-function nil
     "Function called by `my-goto' when there is no clocking task."
     :type 'function
     :group 'my-goto)

   (defcustom my-goto-number-function nil
     "Function called by `my-goto' when a numeric prefix is given to it."
     :type 'function
     :group 'my-goto)

   (defcustom my-goto-two-C-u-action 'my-goto-show-current-agenda-buffer
     "Function called when `my-goto' is run with two universal prefixes."
     :type 'function
     :group 'my-goto)

   (defcustom my-goto-default-agenda-command 'org-agenda
     "Default agenda command."
     :type 'function
     :group 'my-goto)

   (defun my-goto (&optional arg)
     (interactive "P")
     (pcase arg
       ('nil (cond
              ((org-clocking-p) (org-clock-goto))
              ((functionp my-goto-default-function) (funcall my-goto-default-function))
              (t (message "I have no idea what to do or where to go."))))
       ('(4) (counsel-org-clock-history))
       ('(16) (funcall my-goto-two-C-u-action))
       ((pred numberp)
        (funcall my-goto-number-function arg))
       (_ (user-error "Invalid arg: %s" arg))))

   (defun my-goto-show-current-agenda-buffer ()
     "Show an existing agenda buffer if any.

   Otherwise, `my-goto-default-agenda-command' is run."
     (let ((buf (or (get-buffer "*Org Agenda*")
                    (internal-complete-buffer "*Org Agenda" nil nil))))
       (cl-etypecase buf
         (null (progn
                 (message "No org-agenda buffer is found. Start a new one")
                 (funcall my-goto-default-agenda-command)))
         (buffer (progn
                   (message "Open an existing agenda buffer")
                   (switch-to-buffer-other-window buf)))
         (listp (progn
                  (message "Opening an agenda buffer: %s" buf)
                  (switch-to-buffer-other-window (car buf)))))))

   (akirak/bind-key "M-g M-j" #'my-goto)
 #+end_src
**** Org anywhere
#+begin_src emacs-lisp
  (akirak/bind-search "M-o" #'helm-org-rifle-known-files)
  (akirak/bind-user
    "c" #'org-capture
    "l" 'org-store-link
    "n" #'counsel-org-capture-string)
#+end_src
**** Frame
:PROPERTIES:
:ID:       5c418e70-a0a0-4d86-81a5-3186abb038ee
:END:

#+begin_src emacs-lisp
  (akirak/define-frame-workflow "org"
    :key "o"
    :layout '(progn
               (org-starter-load-all-known-files)
               (when (fboundp #'ibuffer-sidebar-show-sidebar)
                 (ibuffer-sidebar-show-sidebar)
                 (with-current-buffer (ibuffer-sidebar-buffer (selected-frame))
                   (ibuffer-projectile-set-filter-groups)
                   (ibuffer-update nil))))
    :make-frame '(frame-purpose-make-mode-frame 'org-mode))
#+end_src

**** Org-agenda keybindings                              :Emacs:Org__Mode:
:PROPERTIES:
:CREATED_TIME: [2019-01-19 Sat 12:22]
:END:
:LOGBOOK:
CLOCK: [2019-01-19 Sat 12:22]--[2019-01-19 Sat 12:25] =>  0:03
:END:

#+begin_src emacs-lisp
  (general-def org-agenda-mode-map :package 'org-agenda
    "M-n" #'org-agenda-drag-line-forward
    "M-p" #'org-agenda-drag-line-backward)
#+end_src
*** Beancount
#+begin_src emacs-lisp
  (akirak/require 'setup-beancount)
#+end_src
** Meta
*** TODO Import from the previous configuration
#+begin_src emacs-lisp
  (let ((old-init-file (expand-file-name "old-init.el" user-emacs-directory)))
    (load-file old-init-file)
    (run-with-timer 3 nil
                    `(lambda ()
                       (message "The previous configuration files (%s) still exist. I have to migrate them soon."
                                (abbreviate-file-name ,old-init-file)))))
#+end_src

Review config in the following directories:

- [X] keybindings
- [X] progmodes
- [ ] org
- [X] ui
- [X] apps
- [ ] coding
- [ ] etc
- [X] exwm
- [X] international
- [X] local
- [X] misc
- [X] x

The following modules require further review:

- [ ] [[file:setup/setup-dired.el]]
- [ ] [[file:setup/setup-keybindings.el]]
- [ ] [[file:setup/setup-web-browser.el]]
- [ ] [[file:setup/setup-corefighter.el]]
- [ ] [[file:setup/setup-repom.el]]
