* emacs.d
** Prerequisites
   :PROPERTIES:
   :CUSTOM_ID: prerequisites
   :END:

- Emacs 26.1
- Extra executables such as ripgrep might be needed for some functionalities in this configuration to work

** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

You can use [[https://github.com/akirak/emacs-playground][playground]] to try out this configuration.

To properly install this configuration, first back up your current
configuration and then use Git to clone the repository:

#+BEGIN_EXAMPLE
    git clone https://github.com/akirak/emacs.d.git ~/.emacs.d 
#+END_EXAMPLE

Dependencies and extra configuration files, which are configured in my [[https://github.com/akirak/nixos-config][nixos-config]] repository, can be installed using Nix package manager and [[https://github.com/rycee/home-manager][home-manager]].

After starting Emacs with the configuration, you have to run
=all-the-icons-install-fonts=.

** Overview
Emacs loads [[file:init.el][~/.emacs.d/init.el]], which in turn loads [[file:main.org][main.org]].

** See also
There are great Emacs configuration repositories on GitHub. The following repositories are my favorites:

- [[https://github.com/purcell/emacs.d][emacs.d by Steve Purcell]]
- [[https://github.com/kaushalmodi/.emacs.d][.emacs.d by Kaushal Modi]]

[[https://github.com/alphapapa][Alphapapa (Adam Porter)]] is one of the most active Emacs package developers in the world, and I rely on quite a few packages and ideas by him. I definitely recommend that you take a look at his stuffs if you want to make the most of Emacs.
** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:
MIT License

