* emacs.d
  :PROPERTIES:
  :CUSTOM_ID: emacs.d
  :END:

[[https://travis-ci.org/akirak/emacs.d][https://travis-ci.org/akirak/emacs.d.svg]]

This is my working Emacs configuration.

** Prerequisites
   :PROPERTIES:
   :CUSTOM_ID: prerequisites
   :END:

Emacs 26.1

** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

You can use [[https://github.com/akirak/emacs-playground][playground]]
to try out this configuration.

To properly install this configuration, first back up your current
configuration and then use Git to clone the repository:

#+BEGIN_EXAMPLE
    git clone https://github.com/akirak/emacs.d.git ~/.emacs.d 
#+END_EXAMPLE

This repository ships with an Ansible playbook for extra configuration tasks. It can be triggered by =Makefile= in the repository.

To install dependencies,

#+BEGIN_SRC shell
make deps
#+END_SRC


To activate my personal configuration,

#+BEGIN_SRC shell
make normal
#+END_SRC

To install =~/.xinitrc= for EXWM as well as the personal configuration,

#+BEGIN_SRC shell
make exwm
#+END_SRC

After starting Emacs with the configuration, you have to run
=all-the-icons-install-fonts=.

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

GPL v3
