version: 2
jobs:
  build:
    docker:
      - image: akirak/home.nix
    working_directory:
      ~/.emacs.d
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: nix-shell -p gnumake --run make
