;;; ak-defaults.el --- Settings without external dependencies

;; Ask y or n rather than yes or no
(fset 'yes-or-no-p 'y-or-n-p)

;; Automatically revert the buffer when the file is changed on disk
(global-auto-revert-mode 1)

;; Save per-file cursor positions
(save-place-mode 1)

;; Keep a list of recent files
(recentf-mode 1)

;; Exclude *-autoloads.el mostly generated by straight.el from recent files
(add-to-list 'recentf-exclude
             (expand-file-name "~/\.emacs\.d/straight/build/.+-autoloads\.el"))

;; Highlight matching parentheses
(show-paren-mode 1)

;; Insert parentheses in pair
(electric-pair-mode 1)

;; Disable UI features
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)

;; Enable winner-mode for undoing/redoing the window configuration
(winner-mode 1)

;; Set default coding
(setq-default coding-system-for-read 'utf-8
              coding-system-for-write 'utf-8)

(provide 'init-defaults)
