(require 'init-key-translation)
(require 'init-general)
(require 'init-shell-bindings)
(require 'init-c-x)
(require 'init-c-c)
(require 'init-ctrl-keys)
(require 'init-meta-keys)
(require 'init-func-keys)
(require 'init-menu-keys)
(require 'init-misc-keybindings)

(provide 'init-keybindings)
