(require 'init-company)
(require 'init-hippie-expand)
(require 'init-projectile)
(require 'init-link-hint)
(require 'init-helm-make)
(require 'init-outshine)
(require 'init-outorg)
(require 'init-undo-tree)
(require 'init-yasnippet)
(require 'init-yankpad)
(require 'init-aggressive-indent)
(require 'init-corral)
(require 'init-prog-commands)

(provide 'init-coding)
