(require 'window-go)

(define-obsolete-function-alias 'akirak/bottom-window 'window-go-bottom)
(define-obsolete-function-alias 'akirak/first-file-window 'window-go-first-file-window)
(define-obsolete-function-alias 'akirak/previous-window 'window-go-previous)
(define-obsolete-function-alias 'akirak/select-master-window 'window-go-master)
(define-obsolete-function-alias 'akirak/swap-windows 'window-go-swap)
(define-obsolete-function-alias 'akirak/swap-master-window 'window-go-swap-master)
(define-obsolete-function-alias 'akirak/exwm-pane-grow-horizontally 'window-go-resize-horizontally)
(define-obsolete-function-alias 'akirak/exwm-pane-shrink-horizontally 'window-go-shrink-horizontally)
(define-obsolete-function-alias 'akirak/exwm-pane-shrink 'window-go-shrink)
(define-obsolete-function-alias 'akirak/exwm-pane-grow 'window-go-grow)
(define-obsolete-function-alias 'akirak/split-window-sensibly 'window-go-split-sensibly)
(define-obsolete-function-alias 'akirak/spawn-terminal 'window-go-term-in-split-window)

(provide 'init-exwm-utils)
