#!/bin/sh

git submodule update --init --recursive

# Based on https://gist.github.com/Quintok/815396509ff79d886656b2855e1a8a46

# A pre-push hook based on the git template. This will verify that no WIP or
# autosquash commits are present. If such a commit is present, pushing will not
# be possible.

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
  if [ "$local_sha" = $z40 ]
  then
    # Ignore delete
    :
  else
    if [ "$remote_sha" = $z40 ]
    then
      # New branch, examine all commits since master
      range="$(git merge-base $local_sha master)..$local_sha"
    else
      # Update to existing branch, examine new commits
      range="$remote_sha..$local_sha"
    fi

    # Check for WIP commits
    commit=`git rev-list -n 1 --grep '^WIP' "$range"`
    if [ "$remote" = master -a -n "$commit" ]
    then
      echo "\nPush rejected: WIP commit detected\n"
      exit 1
    fi

    # Check for autosquash commits
    commit=`git rev-list -n 1 --grep '^\(fixup\|squash\)!' "$range"`
    if [ -n "$commit" ]
    then
      echo "\nPush rejected: autosquash commit detected\n"
      exit 1
    fi
  fi
done

git diff --exit-code --name-status HEAD
if [ $? -gt 0 ]; then
    echo "Pre-push tests are prevented if the working tree is dirty" >&2
    exit 1
fi

make test
