name: build
on:
  push:
    branches:
    - maint
    paths-ignore:
    - '**.md'
    - '**.org'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: cachix use emacs-ci
    - run: nix-build
